version: '3'
services:

  database:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=simple-spring-crud
      - MYSQL_PASSWORD=simplepassword
      - MYSQL_DATABASE=simple-spring-crud
